# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SeedexCli < Formula
  desc "Seedex CLI — relay sync daemon for the Seedex desktop bridge"
  homepage "https://github.com/wishworldbetter/seedex"
  version "0.6.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wishworldbetter/seedex/releases/download/v0.6.6/seedex-cli_darwin_amd64.tar.gz"
      sha256 "80a7fc56b608f67e96f1532dc4099f327bbc0d179985fcdf31fdbe5aef0645e5"

      define_method(:install) do
        bin.install "seedex-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wishworldbetter/seedex/releases/download/v0.6.6/seedex-cli_darwin_arm64.tar.gz"
      sha256 "40bfae6d4958620cd715ce5f9aa3a812f02799105f05390917a5350f20d6a255"

      define_method(:install) do
        bin.install "seedex-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wishworldbetter/seedex/releases/download/v0.6.6/seedex-cli_linux_amd64.tar.gz"
      sha256 "fdc57792a165359e0963e1255e23684c0f2d5f7ebfff11eb7faa58cf84f6664d"
      define_method(:install) do
        bin.install "seedex-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wishworldbetter/seedex/releases/download/v0.6.6/seedex-cli_linux_arm64.tar.gz"
      sha256 "e6e06089066dcf21191dd62274f1b501f6eb8c73aeb04f4458ef9de4e0736e6d"
      define_method(:install) do
        bin.install "seedex-cli"
      end
    end
  end

  test do
    system "#{bin}/seedex-cli", "version"
  end
end
