# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SeedexCli < Formula
  desc "Seedex CLI — relay sync daemon for the Seedex desktop bridge"
  homepage "https://github.com/wishworldbetter/seedex"
  version "0.3.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wishworldbetter/seedex/releases/download/v0.3.5/seedex-cli_darwin_amd64.tar.gz"
      sha256 "4b19fee55776180469ca2304b57ddbfad11b757aa0aae08879e922957b73e110"

      define_method(:install) do
        bin.install "seedex-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wishworldbetter/seedex/releases/download/v0.3.5/seedex-cli_darwin_arm64.tar.gz"
      sha256 "d7e67f8a88e3904e0acc69d1c2d04a038f571641d40a203d493b5dd9678514ca"

      define_method(:install) do
        bin.install "seedex-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wishworldbetter/seedex/releases/download/v0.3.5/seedex-cli_linux_amd64.tar.gz"
      sha256 "27c179891c24d23a750dd41433514513d3f0dc0fdcb896df21482af311f365c5"
      define_method(:install) do
        bin.install "seedex-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wishworldbetter/seedex/releases/download/v0.3.5/seedex-cli_linux_arm64.tar.gz"
      sha256 "45a55ef4822b440b0a6792543c389f3b0781e07d097d8cd376e931eb301f97e6"
      define_method(:install) do
        bin.install "seedex-cli"
      end
    end
  end

  test do
    system "#{bin}/seedex-cli", "version"
  end
end
