# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SeedexCli < Formula
  desc "Seedex CLI — relay sync daemon for the Seedex desktop bridge"
  homepage "https://github.com/wishworldbetter/seedex"
  version "0.5.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wishworldbetter/seedex/releases/download/v0.5.1/seedex-cli_darwin_amd64.tar.gz"
      sha256 "574b2650a1b9740c1b7517f5bb63aa34ca5830ca21c8de9b453989137c5e92e5"

      define_method(:install) do
        bin.install "seedex-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wishworldbetter/seedex/releases/download/v0.5.1/seedex-cli_darwin_arm64.tar.gz"
      sha256 "bc5de684f59dea7ccad7700da4c44c7379f33d09fa06f6b6281e4d9db557f5e4"

      define_method(:install) do
        bin.install "seedex-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wishworldbetter/seedex/releases/download/v0.5.1/seedex-cli_linux_amd64.tar.gz"
      sha256 "26c95f36e5522fbcbb160fbac51ae0b4e6a0c60a011e197d3c2873f9053c5f9a"
      define_method(:install) do
        bin.install "seedex-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wishworldbetter/seedex/releases/download/v0.5.1/seedex-cli_linux_arm64.tar.gz"
      sha256 "dda497622890e4a77298c3ab213acef818a94fd1389d5d4fbb816c34b47c7b5a"
      define_method(:install) do
        bin.install "seedex-cli"
      end
    end
  end

  test do
    system "#{bin}/seedex-cli", "version"
  end
end
